import { IBetSlip } from "./model";

export const mockGames: IBetSlip[] = [
  {
    homeTeam: "Manchester United",
    awayTeam: "Liverpool",
    date: "2024-04-07",
    league: "Premier League",
    homePicked: false,
    drawPicked: false,
    awayPicked: false,
  },
  {
    homeTeam: "Real Madrid",
    awayTeam: "Barcelona",
    date: "2024-04-08",
    league: "La Liga",
    homePicked: false,
    drawPicked: false,
    awayPicked: false,
  },
  {
    homeTeam: "Bayern Munich",
    awayTeam: "Borussia Dortmund",
    date: "2024-04-09",
    league: "Bundesliga",
    homePicked: false,
    drawPicked: false,
    awayPicked: false,
  },
  {
    homeTeam: "Paris Saint-Germain",
    awayTeam: "Olympique Marseille",
    date: "2024-04-10",
    league: "Ligue 1",
    homePicked: false,
    drawPicked: false,
    awayPicked: false,
  },
  {
    homeTeam: "Chelsea",
    awayTeam: "Arsenal",
    date: "2024-04-11",
    league: "Premier League",
    homePicked: false,
    drawPicked: false,
    awayPicked: false,
  },
  {
    homeTeam: "Juventus",
    awayTeam: "AC Milan",
    date: "2024-04-12",
    league: "Serie A",
    homePicked: false,
    drawPicked: false,
    awayPicked: false,
  },
  {
    homeTeam: "Atletico Madrid",
    awayTeam: "Sevilla",
    date: "2024-04-13",
    league: "La Liga",
    homePicked: false,
    drawPicked: false,
    awayPicked: false,
  },
  {
    homeTeam: "Manchester City",
    awayTeam: "Tottenham Hotspur",
    date: "2024-04-14",
    league: "Premier League",
    homePicked: false,
    drawPicked: false,
    awayPicked: false,
  },
];
