export type BetSlipGameStatus = "Preparing" | "Started" | "Running" | "Ended";
export type GameResult = "home" | "draw" | "away";

interface Game {
  opponent1: string;
  opponent2: string;
  GameDateTime: Date;
  gameLeague: string;
  GameResult: GameResult;
  finalResult: number;
}

interface ABetSlip {
  games: Game[];
  status: BetSlipGameStatus;
  date: Date;
}

export const betslips: ABetSlip[] = [
  {
    games: [
      {
        opponent1: "Manchester City",
        opponent2: "Chelsea",
        GameDateTime: new Date(2024, 2, 4),
        gameLeague: "Premier League",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Liverpool",
        opponent2: "Manchester United",
        GameDateTime: new Date(2024, 2, 5),
        gameLeague: "Premier League",
        GameResult: "draw",
        finalResult: 1,
      },
      {
        opponent1: "Tottenham Hotspur",
        opponent2: "Arsenal",
        GameDateTime: new Date(2024, 2, 6),
        gameLeague: "Premier League",
        GameResult: "away",
        finalResult: 3,
      },
      {
        opponent1: "AC Milan",
        opponent2: "Inter Milan",
        GameDateTime: new Date(2024, 2, 7),
        gameLeague: "Serie A",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Real Madrid",
        opponent2: "Barcelona",
        GameDateTime: new Date(2024, 2, 8),
        gameLeague: "La Liga",
        GameResult: "draw",
        finalResult: 2,
      },
      {
        opponent1: "Bayern Munich",
        opponent2: "Borussia Dortmund",
        GameDateTime: new Date(2024, 2, 9),
        gameLeague: "Bundesliga",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Juventus",
        opponent2: "Napoli",
        GameDateTime: new Date(2024, 2, 10),
        gameLeague: "Serie A",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Paris Saint-Germain",
        opponent2: "Lyon",
        GameDateTime: new Date(2024, 2, 11),
        gameLeague: "Ligue 1",
        GameResult: "draw",
        finalResult: 0,
      },
      {
        opponent1: "Chelsea",
        opponent2: "Liverpool",
        GameDateTime: new Date(2024, 2, 12),
        gameLeague: "Premier League",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Arsenal",
        opponent2: "Manchester City",
        GameDateTime: new Date(2024, 2, 13),
        gameLeague: "Premier League",
        GameResult: "home",
        finalResult: 3,
      },
      {
        opponent1: "Inter Milan",
        opponent2: "AC Milan",
        GameDateTime: new Date(2024, 2, 14),
        gameLeague: "Serie A",
        GameResult: "draw",
        finalResult: 2,
      },
      {
        opponent1: "Barcelona",
        opponent2: "Real Madrid",
        GameDateTime: new Date(2024, 2, 15),
        gameLeague: "La Liga",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Borussia Dortmund",
        opponent2: "Bayern Munich",
        GameDateTime: new Date(2024, 2, 16),
        gameLeague: "Bundesliga",
        GameResult: "home",
        finalResult: 2,
      },
    ],
    date: new Date(2024, 6, 5),
    status: "Preparing",
  },
  {
    games: [
      {
        opponent1: "Manchester City",
        opponent2: "Chelsea",
        GameDateTime: new Date(2024, 2, 4),
        gameLeague: "Premier League",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Liverpool",
        opponent2: "Manchester United",
        GameDateTime: new Date(2024, 2, 5),
        gameLeague: "Premier League",
        GameResult: "draw",
        finalResult: 1,
      },
      {
        opponent1: "Tottenham Hotspur",
        opponent2: "Arsenal",
        GameDateTime: new Date(2024, 2, 6),
        gameLeague: "Premier League",
        GameResult: "away",
        finalResult: 3,
      },
      {
        opponent1: "AC Milan",
        opponent2: "Inter Milan",
        GameDateTime: new Date(2024, 2, 7),
        gameLeague: "Serie A",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Real Madrid",
        opponent2: "Barcelona",
        GameDateTime: new Date(2024, 2, 8),
        gameLeague: "La Liga",
        GameResult: "draw",
        finalResult: 2,
      },
      {
        opponent1: "Bayern Munich",
        opponent2: "Borussia Dortmund",
        GameDateTime: new Date(2024, 2, 9),
        gameLeague: "Bundesliga",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Juventus",
        opponent2: "Napoli",
        GameDateTime: new Date(2024, 2, 10),
        gameLeague: "Serie A",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Paris Saint-Germain",
        opponent2: "Lyon",
        GameDateTime: new Date(2024, 2, 11),
        gameLeague: "Ligue 1",
        GameResult: "draw",
        finalResult: 0,
      },
      {
        opponent1: "Chelsea",
        opponent2: "Liverpool",
        GameDateTime: new Date(2024, 2, 12),
        gameLeague: "Premier League",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Arsenal",
        opponent2: "Manchester City",
        GameDateTime: new Date(2024, 2, 13),
        gameLeague: "Premier League",
        GameResult: "home",
        finalResult: 3,
      },
      {
        opponent1: "Inter Milan",
        opponent2: "AC Milan",
        GameDateTime: new Date(2024, 2, 14),
        gameLeague: "Serie A",
        GameResult: "draw",
        finalResult: 2,
      },
      {
        opponent1: "Barcelona",
        opponent2: "Real Madrid",
        GameDateTime: new Date(2024, 2, 15),
        gameLeague: "La Liga",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Borussia Dortmund",
        opponent2: "Bayern Munich",
        GameDateTime: new Date(2024, 2, 16),
        gameLeague: "Bundesliga",
        GameResult: "home",
        finalResult: 2,
      },
    ],
    status: "Started",
    date: new Date(2024, 4, 5),
  },
  {
    games: [
      {
        opponent1: "Manchester City",
        opponent2: "Chelsea",
        GameDateTime: new Date(2024, 2, 4),
        gameLeague: "Premier League",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Liverpool",
        opponent2: "Manchester United",
        GameDateTime: new Date(2024, 2, 5),
        gameLeague: "Premier League",
        GameResult: "draw",
        finalResult: 1,
      },
      {
        opponent1: "Tottenham Hotspur",
        opponent2: "Arsenal",
        GameDateTime: new Date(2024, 2, 6),
        gameLeague: "Premier League",
        GameResult: "away",
        finalResult: 3,
      },
      {
        opponent1: "AC Milan",
        opponent2: "Inter Milan",
        GameDateTime: new Date(2024, 2, 7),
        gameLeague: "Serie A",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Real Madrid",
        opponent2: "Barcelona",
        GameDateTime: new Date(2024, 2, 8),
        gameLeague: "La Liga",
        GameResult: "draw",
        finalResult: 2,
      },
      {
        opponent1: "Bayern Munich",
        opponent2: "Borussia Dortmund",
        GameDateTime: new Date(2024, 2, 9),
        gameLeague: "Bundesliga",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Juventus",
        opponent2: "Napoli",
        GameDateTime: new Date(2024, 2, 10),
        gameLeague: "Serie A",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Paris Saint-Germain",
        opponent2: "Lyon",
        GameDateTime: new Date(2024, 2, 11),
        gameLeague: "Ligue 1",
        GameResult: "draw",
        finalResult: 0,
      },
      {
        opponent1: "Chelsea",
        opponent2: "Liverpool",
        GameDateTime: new Date(2024, 2, 12),
        gameLeague: "Premier League",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Arsenal",
        opponent2: "Manchester City",
        GameDateTime: new Date(2024, 2, 13),
        gameLeague: "Premier League",
        GameResult: "home",
        finalResult: 3,
      },
      {
        opponent1: "Inter Milan",
        opponent2: "AC Milan",
        GameDateTime: new Date(2024, 2, 14),
        gameLeague: "Serie A",
        GameResult: "draw",
        finalResult: 2,
      },
      {
        opponent1: "Barcelona",
        opponent2: "Real Madrid",
        GameDateTime: new Date(2024, 2, 15),
        gameLeague: "La Liga",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Borussia Dortmund",
        opponent2: "Bayern Munich",
        GameDateTime: new Date(2024, 2, 16),
        gameLeague: "Bundesliga",
        GameResult: "home",
        finalResult: 2,
      },
    ],
    status: "Running",
    date: new Date(2024, 4, 5),
  },
  {
    games: [
      {
        opponent1: "Manchester City",
        opponent2: "Chelsea",
        GameDateTime: new Date(2024, 2, 4),
        gameLeague: "Premier League",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Liverpool",
        opponent2: "Manchester United",
        GameDateTime: new Date(2024, 2, 5),
        gameLeague: "Premier League",
        GameResult: "draw",
        finalResult: 1,
      },
      {
        opponent1: "Tottenham Hotspur",
        opponent2: "Arsenal",
        GameDateTime: new Date(2024, 2, 6),
        gameLeague: "Premier League",
        GameResult: "away",
        finalResult: 3,
      },
      {
        opponent1: "AC Milan",
        opponent2: "Inter Milan",
        GameDateTime: new Date(2024, 2, 7),
        gameLeague: "Serie A",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Real Madrid",
        opponent2: "Barcelona",
        GameDateTime: new Date(2024, 2, 8),
        gameLeague: "La Liga",
        GameResult: "draw",
        finalResult: 2,
      },
      {
        opponent1: "Bayern Munich",
        opponent2: "Borussia Dortmund",
        GameDateTime: new Date(2024, 2, 9),
        gameLeague: "Bundesliga",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Juventus",
        opponent2: "Napoli",
        GameDateTime: new Date(2024, 2, 10),
        gameLeague: "Serie A",
        GameResult: "home",
        finalResult: 2,
      },
      {
        opponent1: "Paris Saint-Germain",
        opponent2: "Lyon",
        GameDateTime: new Date(2024, 2, 11),
        gameLeague: "Ligue 1",
        GameResult: "draw",
        finalResult: 0,
      },
      {
        opponent1: "Chelsea",
        opponent2: "Liverpool",
        GameDateTime: new Date(2024, 2, 12),
        gameLeague: "Premier League",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Arsenal",
        opponent2: "Manchester City",
        GameDateTime: new Date(2024, 2, 13),
        gameLeague: "Premier League",
        GameResult: "home",
        finalResult: 3,
      },
      {
        opponent1: "Inter Milan",
        opponent2: "AC Milan",
        GameDateTime: new Date(2024, 2, 14),
        gameLeague: "Serie A",
        GameResult: "draw",
        finalResult: 2,
      },
      {
        opponent1: "Barcelona",
        opponent2: "Real Madrid",
        GameDateTime: new Date(2024, 2, 15),
        gameLeague: "La Liga",
        GameResult: "away",
        finalResult: 1,
      },
      {
        opponent1: "Borussia Dortmund",
        opponent2: "Bayern Munich",
        GameDateTime: new Date(2024, 2, 16),
        gameLeague: "Bundesliga",
        GameResult: "home",
        finalResult: 2,
      },
    ],
    status: "Ended",
    date: new Date(2024, 4, 2),
  },
];
